import type { Metadata } from 'next'
import localFont from 'next/font/local';
import './globals.css'
import Nav from '@/components/Nav';

const poppins = localFont({
  variable: "--font-poppins",
  src: [
    {
      path: "./fonts/Poppins-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Poppins-Medium.otf",
      weight: "500",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex flex-col bg-background">
          {children}
          {/* <Footer /> */}
        </main>
      </body>
    </html>
  )
}
